package com.treasure.data

/**
  * Created by gcrowell on 2017-06-24.
  */
object DataService {

  import org.apache.spark.sql.SparkSession

  val spark: SparkSession = SparkSession.builder
    .appName("My Spark Application") // optional and will be autogenerated if not specified
    .master("local[*]") // avoid hardcoding the deployment environment
    //      .enableHiveSupport() // self-explanatory, isn't it?
    .config("spark.sql.warehouse.dir", "target/spark-warehouse")
    .getOrCreate




}
